# Generated by Django 3.1.1 on 2020-09-30 00:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Efnisflokkur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efnisflokkur', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_heiti', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fletta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uppflettiord', models.CharField(max_length=255)),
                ('beygingarmynd', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_id', models.IntegerField(blank=True, null=True)),
                ('upptaka', models.FileField(blank=True, null=True, upload_to='fletta_sounds')),
                ('ipa', models.CharField(blank=True, max_length=255, null=True)),
                ('ordmynd', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('buin', models.BooleanField(default=False)),
                ('efnisflokkur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.efnisflokkur')),
            ],
        ),
        migrations.CreateModel(
            name='Malsnid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malsnid', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_heiti', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordflokkur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordflokkur', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_heiti', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordastaeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordastaeda', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_thyd', models.CharField(blank=True, max_length=255, null=True)),
                ('mynd', models.ImageField(blank=True, null=True, upload_to='fletta_images')),
                ('efnisflokkur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.efnisflokkur')),
                ('malsnid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.malsnid')),
                ('uppflettiord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.fletta')),
            ],
        ),
        migrations.CreateModel(
            name='JpJafnheiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_jafnheiti', models.CharField(max_length=255)),
                ('ath', models.CharField(blank=True, max_length=700, null=True)),
                ('mynd', models.ImageField(blank=True, null=True, upload_to='fletta_images')),
                ('uppflettiord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.fletta')),
            ],
        ),
        migrations.AddField(
            model_name='fletta',
            name='malsnid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.malsnid'),
        ),
        migrations.AddField(
            model_name='fletta',
            name='ordflokkur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.ordflokkur'),
        ),
        migrations.CreateModel(
            name='DaemiOrdastaeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daemi_ordastaeda', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_thyd', models.CharField(blank=True, max_length=700, null=True)),
                ('ordastaeda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.ordastaeda')),
                ('uppflettiord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.fletta')),
            ],
        ),
        migrations.CreateModel(
            name='Daemi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daemi', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_thyg', models.CharField(blank=True, max_length=700, null=True)),
                ('jp_jafnheiti', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.jpjafnheiti')),
                ('uppflettiord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fletta.fletta')),
            ],
        ),
    ]
